# Generated by Django 2.2.5 on 2019-09-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('missing_count', models.IntegerField()),
                ('source', models.URLField()),
            ],
        ),
    ]
