# Generated by Django 2.2.5 on 2019-09-24 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_recipe_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='users',
        ),
        migrations.AddField(
            model_name='recipe',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
