# Generated by Django 2.2.5 on 2019-09-24 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20190924_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='users',
        ),
    ]
