# Generated by Django 2.2.5 on 2019-09-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='missing_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
